# Generated by Django 5.1.4 on 2024-12-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_descricao_curso_preco_alter_curso_capa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecursos',
            name='tipo_aquisicao',
            field=models.CharField(choices=[('ganhado', 'Ganhado'), ('comprado', 'Comprado')], default='comprado', max_length=20),
        ),
    ]
