# Generated by Django 5.1.4 on 2024-12-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_profile_cpf_alter_clientecursos_tipo_aquisicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
